In [22]:
import numpy as np

# Create the 2D array
my_array = np.array([[11, 12, 13, 14],
                     [15, 16, 17, 18]])
print(my_array)
# Creating arrays
# 1. Create an array with 4 rows and 3 columns of zeros
zeros_array = np.zeros((4, 3))
print("1. Zeros array:\n", zeros_array)

# 2. Create an array of ones that has 3 rows and 4 columns
ones_array = np.ones((3, 4))
print("\n2. Ones array:\n", ones_array)

# 3. Create an array containing integers 4 to 13 inclusive
int_array = np.arange(4, 14)
print("\n3. Integer array:", int_array)

# 4. Create an array containing [0., 1.5, 3., 4.5]
float_array = np.array([0., 1.5, 3., 4.5])
print("\n4. Float array:", float_array)

# 5. Create a 2 by 2 array containing '4' in each position
four_array = np.full((2, 2), 4)
print("\n5. Array with '4' in each position:\n", four_array)

# 6. Create matrices
# i. Identity matrix of size 4
identity_matrix = np.eye(4)
print("\n6.i. Identity matrix of size 4:\n", identity_matrix)

# ii. Diagonal matrix with [10,12] as the diagonals
diagonal_matrix = np.diag([10, 12])
print("\n6.ii. Diagonal matrix with [10, 12] as diagonals:\n", diagonal_matrix)

# 7. Create a 3 by 3 array with random floats in [0, 10]
random_floats_array = np.random.uniform(0, 10, (3, 3))
print("\n7. Array with random floats in [0, 10]:\n", random_floats_array)

# 8. Create a 3 by 3 array with random integers in [10, 20]
random_integers_array = np.random.randint(10, 21, (3, 3))
print("\n8. Array with random integers in [10, 20]:\n", random_integers_array)

#slicing arrays
# 1. Use this array for the following practice:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])

# a. Get a subarray of the first row and first 2 columns
sub_array = myArray[0, :2]
print("a. Subarray of the first row and first 2 columns:", sub_array)

# b. Change all elements in 1st and second row to 0
myArray[:2, :] = 0
print("\nb. Array after changing elements in the first two rows to 0:\n", myArray)

# 2. Create an array that contains [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] and reverse the order.
array_reverse = np.arange(21)
array_reverse = np.flip(array_reverse)
print("\nReversed array:", array_reverse)

#RESHAPING
# Use the given array
myArray = np.array([[11,12,13], [14,15,16]])

# Reshape the array to have 3 rows
reshaped_array = myArray.reshape(3, -1)

print("Reshaped array with 3 rows:\n", reshaped_array)

#math
# Use the given array
myArray = np.arange(10)

# 1. Find the square of every number in array
squared_array = np.square(myArray)
print("1. Square of every number in the array:", squared_array)

# 2. Find the square root of every number in array
sqrt_array = np.sqrt(myArray)
print("\n2. Square root of every number in the array:", sqrt_array)

# 3. Multiply the square of each number in array with its respective square root
result_array = squared_array * sqrt_array
print("\n3. Result after multiplying the square of each number with its respective square root:", result_array)

#ADDING ELEMENTS
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])

# 1. Add a new row of elements containing 20, 21, and 22
new_row = np.array([[20, 21, 22]])
myArray = np.concatenate((myArray, new_row), axis=0)
print("1. Array after adding a new row:\n", myArray)

# 2. Add a new column of elements containing 30, 40, and 50
new_column = np.array([[30], [40], [50]])
myArray = np.concatenate((myArray, new_column), axis=1)
print("\n2. Array after adding a new column:\n", myArray)

#INSERTING ELEMENT
myArray = np.zeros((2, 2))
myArray = np.insert(myArray, 2, 1, axis=1)
print("1. Array after adding 1 column of 1:\n", myArray)

# 2. Add 2 rows of 2 to the answer from part 1
myArray = np.insert(myArray, 2, 2, axis=0)
print("\n2. Array after adding 2 rows of 2:\n", myArray)

# 3. Remove the last column
myArray = np.delete(myArray, -1, axis=1)
print("\n3. Array after removing the last column:\n", myArray)

# 4. Remove the last row
myArray = np.delete(myArray, -1, axis=0)
print("\n4. Array after removing the last row:\n", myArray)

#DELETING ELEMENTS
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])

# Remove the middle column
myArray = np.delete(myArray, 1, axis=1)

print("Array after removing the middle column:\n", myArray)

#TEST EXERCISE
#Replace all odd numbers in the given array with -1
# Given array
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Replace odd numbers with -1
exercise_1[exercise_1 % 2 != 0] = -1

print("Modified array:", exercise_1)

#Convert a 1-D array into a 2-D array with 3 rows
# Given array
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Reshape the array to have 3 rows
exercise_2_reshaped = exercise_2.reshape(3, -1)

print("2-D array with 3 rows:\n", exercise_2_reshaped)
#Add 202 to all the values in given array
# Given array
exercise_3 = np.arange(4).reshape(2, -1)

# Add 202 to all values in the array
exercise_3 += 202

print("Modified array:\n", exercise_3)

#Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
random_integers = np.random.randint(30, 41, size=10)

print("Random integers between 30 and 40:", random_integers)

# Given arrays
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

# Find positions where x > y
positions_greater = np.where(x > y)

# Find positions where x == y
positions_equal = np.where(x == y)

print("Positions where x > y:", positions_greater)
print("Positions where x == y:", positions_equal)
# Given array
exercise_6 = np.arange(100).reshape(5, -1)

# Extract the first four columns
first_four_columns = exercise_6[:, :4]

print("First four columns of the array:\n", first_four_columns)


[[11 12 13 14]
 [15 16 17 18]]
1. Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

2. Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3. Integer array: [ 4  5  6  7  8  9 10 11 12 13]

4. Float array: [0.  1.5 3.  4.5]

5. Array with '4' in each position:
 [[4 4]
 [4 4]]

6.i. Identity matrix of size 4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

6.ii. Diagonal matrix with [10, 12] as diagonals:
 [[10  0]
 [ 0 12]]

7. Array with random floats in [0, 10]:
 [[3.0385445  8.12112277 5.75601177]
 [9.84510441 9.17655515 4.98054464]
 [2.85939424 3.27870379 1.75501915]]

8. Array with random integers in [10, 20]:
 [[12 13 10]
 [13 12 14]
 [19 19 19]]
a. Subarray of the first row and first 2 columns: [11 12]

b. Array after changing elements in the first two rows to 0:
 [[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]

Reversed array: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
Reshaped array with 3 rows:
 [[11 12]
 [13 14]
 [15 16]]
1. Sq

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3